// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS_XyNZ7uVwMsGHOLRLeISMh7VNtEPT0E',
    appId: '1:426177739881:web:a8affd0f43ef2ed17236f8',
    messagingSenderId: '426177739881',
    projectId: 'sgopaluni1-cmsc5303-flutter',
    authDomain: 'sgopaluni1-cmsc5303-flutter.firebaseapp.com',
    storageBucket: 'sgopaluni1-cmsc5303-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3a9k7VEBIZ5oXHXEHT8N0vxCo40O3edI',
    appId: '1:426177739881:android:dcbfb6bfdf6ef68d7236f8',
    messagingSenderId: '426177739881',
    projectId: 'sgopaluni1-cmsc5303-flutter',
    storageBucket: 'sgopaluni1-cmsc5303-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN3034e_7zoZruoHRxVudCJ7lJKr7inBU',
    appId: '1:426177739881:ios:ea6c2627b4f0ffba7236f8',
    messagingSenderId: '426177739881',
    projectId: 'sgopaluni1-cmsc5303-flutter',
    storageBucket: 'sgopaluni1-cmsc5303-flutter.appspot.com',
    iosBundleId: 'edu.uco.sgopaluni1.cmsc5303.lesson6',
  );

}